# Generated by Django 3.2.18 on 2023-05-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_users',
        ),
    ]
